[common]	
env = "development" # development|production
js = "bundle.js" # Auto-prefixed with root
style = "bundle.css" # Auto-prefixed with root
static = "static" # Images, stubs, etc
api = "/api/" # prefix for api endpoints 

[server]
template = "template.html.tpl"
address = "localhost:8888"

[client]
entry = "entry.js"
