[common]	
env = "development" # development|production
static = "static" # Bundles, images, stubs, etc. 
js = "bundle.js" # Auto-prefixed with static 
style = "bundle.css" # Auto-prefixed with static 
api = "/api/" # prefix for api endpoints 
hot = true # enables live reload. env must be development and hmr must be set
hmr = "localhost:8889" # when hot flag is true the bundle is served via jsonp from webpack server 

[server]
template = "template.html.tpl"
address = "localhost:8888"
# when env is production it will prefix bundles with the serve option
# this is useful for reverse proxies
serve = "example.com"

[client]
entry = "entry.js"
